//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Transaction
    {
        [Key]
        public int transactionID { get; set; }
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(10, 2)")]
        [Range(1, int.MaxValue, ErrorMessage = "Amount should be greater than 0.")]
        public int transactionAmount { get; set; }
        [Column(TypeName = "nvarchar(75)")]
        public string transactionNote { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime transactionDate { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Please select a category.")]
        public int categoryID { get; set; }
        public virtual Category Category { get; set; }

        [NotMapped]
        public string CategoryTitleWithIcon
        {
            get
            {
                return Category == null ? "" : Category.categoryIcon + " " + Category.categoryTitle;
            }
        }

        [NotMapped]
        public string FormattedAmount
        {
            get
            {
                return ((Category == null || Category.categoryType == "Expense") ? "- " : "+ ") + transactionAmount.ToString("N0");
            }
        }

        [NotMapped]
        public string FormattedDate
        {
            get
            {
                return transactionDate.ToString("yyyy-MM-dd");
            }
        }
    }
}
